In [1]:
import math

class RandomNumberGenerator:
    def __init__(self, seedVaule=None):
        self.__seed=seedVaule
    def nextInt(self, low, high):
        m = 2147483647
        a = 16807
        b = 127773
        c = 2836
        k = int(self.__seed / b)
        self.__seed = a * (self.__seed % b) - k * c
        if self.__seed < 0:
            self.__seed = self.__seed + m
        value_0_1 = self.__seed
        value_0_1 =  value_0_1/m
        return low + int(math.floor(value_0_1 * (high - low + 1)))
    def nextFloat(self, low, high):
        low*=100000
        high*=100000
        val = self.nextInt(low,high)/100000.0
        return val


In [2]:
import numpy as np
import random
import copy
import time

siz1and2 = 50
rand_min = 1
rand_max = 50
R = RandomNumberGenerator(10)
flow =  np.array([[R.nextInt(rand_min, rand_max) for _ in range(siz1and2)] for _ in range(siz1and2)])
distances =  np.array([[R.nextInt(rand_min, rand_max) for _ in range(siz1and2)] for _ in range(siz1and2)])
print(flow)
print(len(flow), len(flow[0]), len(distances))


[[ 1 16 28 ... 43 37 19]
 [34 39 19 ... 21 35  8]
 [19 34 44 ... 33 27 45]
 ...
 [29 49 49 ...  1  4 32]
 [36  9 42 ...  7 42 18]
 [ 8 43 32 ... 35 34 32]]
50 50 50


In [8]:
class QAP_RS :
    
    def __init__(self, flow, distances, max_iter=5000):
        self.flow = flow
        self.distances = distances
        self.best_cost = 999999999
        self.solution = self.find_first()
        #print(len(flow), len(flow[0]), len(distances), len(distances[0], len(solution)))
        self.max_iter = max_iter
        
    #def find_first(self):
    #    for i in range(1):#self.max_iter):
    #        ret = []
    #        while len(ret < len(self.distances)):
    #            x = R.nextInt(0,len(distances))
    #            if x not in ret:
    #                ret.append(x)
    #        return ret

    def find_first(self):
        
        for i in range(1):#self.max_iter):
            cost_min = 99999999
            cost_max = -99999999
            solution = []
            some_random_solution = []
            for j in range(1000):
                while len(some_random_solution) < len(self.distances):
                    x = R.nextInt(0,len(distances)-1)
                    if x not in some_random_solution:
                        some_random_solution.append(x)
                if self.cost_function(some_random_solution) < cost_min:
                    cost_min = self.cost_function(some_random_solution)
                    solution = some_random_solution
                if self.cost_function(some_random_solution) > cost_max:
                    cost_max = self.cost_function(some_random_solution)
            #self.rozstep = cost_max-cost_min
            #self.temp = self.rozstep * self.rozstep_temp_factor
            print('sposrod losowych najlepszy cost_min, cost_max')
            print(cost_min, cost_max)
            return solution
            #return np.arange(0,len(self.flow))
                       
    def cost_function (self, solution):
        cost = 0
        i = 0
        for i in range(len(self.flow)):
            for j in range(len(self.flow[0])):
                cost += self.distances[i][j] * self.flow[solution[i]][solution[j]]
        return cost

    def flip_model_and_update(self):
        def find_pair(solution):
            return ( R.nextInt(0,len(solution)-1) , R.nextInt(0,len(solution)-1) ) 
        pair = find_pair(self.solution)
        solution_new = copy.deepcopy(self.solution)
        solution_new[pair[0]] = self.solution[pair[1]]
        solution_new[pair[1]] = self.solution[pair[0]]
        cost_new = self.cost_function(solution_new)
        if cost_new < self.best_cost:
            self.best_cost = cost_new
            self.solution = solution_new
        return

    def update_models(self):
        for i in range(self.max_iter):
            self.flip_model_and_update()
            


q = QAP_RS(flow, distances)
print(q.solution)
print(q.cost_function(q.solution))
Q = copy.deepcopy(q)
 

rets = []
#q.flip_model_and_update()
for max_iter in [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]: ## jak da sie 9000 to bedzie mniej niz 
#for max_iter in [4500, 5000, 5001]:
    R = RandomNumberGenerator(100)
#for max_iter in [5, 10]:
    q = copy.deepcopy(Q)
    q.max_iter = max_iter
#tim = time.time()
    start_time = time.time()
    q.update_models()
    #print(q.solution)
    print()
    print(max_iter, q.cost_function(q.solution))
    tim =  time.time()-start_time
    print('time: ',tim)
    rets.append((max_iter, tim))

#3000 1513091

#5000 1516114

sposrod losowych najlepszy cost_min, cost_max
1654402 1654402
[18, 12, 21, 42, 32, 2, 27, 20, 11, 36, 34, 44, 49, 23, 16, 30, 0, 17, 26, 10, 28, 47, 29, 40, 13, 41, 37, 1, 22, 48, 19, 14, 8, 4, 43, 7, 33, 24, 15, 46, 45, 35, 6, 31, 39, 9, 5, 38, 25, 3]
1654402

1000 1536432
time:  1.715381383895874

2000 1525783
time:  3.286954402923584

3000 1520402
time:  6.509231805801392

4000 1516893
time:  6.476776123046875

5000 1514177
time:  9.677934169769287

6000 1512838
time:  11.383301258087158

7000 1511905
time:  13.099725008010864

8000 1511274
time:  14.925838232040405

9000 1508687
time:  16.129855632781982
